query GetProposalById($votingProposalId: BigInt!) {
  votingProposalCreateds(where: { votingProposalId: $votingProposalId }) {
    creator
    creationDate
    conclusionDate
    proposalHash
    votingProposalId
  }
}