query GetProposals {
  votingProposalCreateds(first: 10, where: {}, orderBy: votingProposalId) {
    creator
    creationDate
    conclusionDate
    proposalHash
    votingProposalId
    blockNumber
  }
}